// Generated by Wrangler by running `wrangler types`

interface Env {
	CLERK_SECRET_KEY: string
	CLERK_PUBLISHABLE_KEY: string
	CLOUDFLARE_ACCOUNT_ID: string
	BETTER_AUTH_SECRET: string
	DB: D1Database
	USER_TRACKING: AnalyticsEngineDataset
}
