name = "electric-proxy-api"
main = "src/index.ts"
compatibility_date = "2024-12-05"

compatibility_flags = ["nodejs_compat"]

placement = { mode = "smart" }

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "electric-proxy-db"
database_id = "35f7fdfa-5f60-4d4c-b6cd-b07745f6e38e"
preview_database_id = "local-test-db"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
