name = "electric-proxy-api"
main = "src/index.ts"
compatibility_date = "2024-12-05"

compatibility_flags = ["nodejs_compat"]

placement = { mode = "smart" }

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "electric-proxy-db"
database_id = "35f7fdfa-5f60-4d4c-b6cd-b07745f6e38e"
preview_database_id = "local-test-db"

[[analytics_engine_datasets]]
binding = "USER_TRACKING"
dataset = "electric"
